### ISSUE TITLE
Le format des paths ne marchent pas sous linux

### ISSUE THREAD

**Issue by Stellaris-code** [LugosFingite/RPG#3]
![selection_018](https://user-images.githubusercontent.com/8571612/27760523-a95aeab2-5e49-11e7-9fb6-09c92697a720.png)

**Comment by faremy** [comment]
ça j'ai trouvé comment le fixer (normalement)
dans le fichier Util.py tu rajoutes os.sep = "\\"  et normalement ça règle le problème

**Comment by faremy** [comment]
et bien sur tu fais import os au début du fichier Util.py

**Comment by faremy** [comment]
Paths réparés dans la version finale.
